# Generated by Django 4.2.7 on 2023-12-15 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ManasFilm',
            new_name='ParserModel',
        ),
    ]
