# Generated by Django 4.2.7 on 2023-12-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_rename_manasfilm_parsermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsermodel',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
